"""add learning objectives and achievements

Revision ID: 6b7acbe4abb3
Revises: cec19f568a3f
Create Date: 2026-08-02 07:39:37.488331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b7acbe4abb3'
down_revision: Union[str, None] = 'cec19f568a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_objectives',
    sa.Column('id_learning_objective', sa.Integer(), nullable=False),
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'NATIVE', name='proficiencylevel'), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_language'], ['languages.id_language'], ),
    sa.PrimaryKeyConstraint('id_learning_objective')
    )
    op.create_table('objective_achievements',
    sa.Column('id_objective_achievement', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_learning_objective', sa.Integer(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_learning_objective'], ['learning_objectives.id_learning_objective'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_objective_achievement'),
    sa.UniqueConstraint('id_user', 'id_learning_objective', name='uq_user_objective')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objective_achievements')
    op.drop_table('learning_objectives')
    # ### end Alembic commands ###
