"""tables du noyau MVP

Revision ID: c6c2cab80375
Revises: 
Create Date: 2026-07-16 19:12:09.615478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c6c2cab80375'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id_language'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=250), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('learning_sessions',
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=30), nullable=False),
    sa.Column('session_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('resource', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_language'], ['languages.id_language'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_session')
    )
    op.create_table('user_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.String(length=20), nullable=True),
    sa.Column('target_level', sa.String(length=20), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_language'], ['languages.id_language'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'id_language', name='unique_user_language')
    )
    op.create_table('vocabularies',
    sa.Column('id_vocabulary', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=60), nullable=False),
    sa.Column('translation', sa.String(length=60), nullable=False),
    sa.Column('definition', sa.String(length=500), nullable=True),
    sa.Column('example', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_language'], ['languages.id_language'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_vocabulary')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabularies')
    op.drop_table('user_languages')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
