"""add created_at to vocabulary

Revision ID: cec19f568a3f
Revises: c6c2cab80375
Create Date: 2026-07-23 06:19:55.311298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cec19f568a3f'
down_revision: Union[str, None] = 'c6c2cab80375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabularies', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabularies', 'created_at')
    # ### end Alembic commands ###
